version: '3'
services:
  postgre:
    image: "postgres"
    volumes:
      - ./docker-cache/postgre:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_database